  # FLP - 2. projekt
  # 23.4.2017
  # Autor: Bc. Lukas Pelanek, xpelan03@stud.fit.vutbr.cz

PROGRAM=flp22-log
SRC=xziska03.pl

CC=swipl
FLAGS=-q

all:
	$(CC) $(FLAGS) -g start -o $(PROGRAM) -c $(SRC)

clean:
	rm $(PROGRAM)
