  # FLP - 2. projekt
  # 29.4.2023
  # Bc. Marek Ziska, xziska03@stud.fit.vutbr.cz

PROGRAM=flp22-log
SRC=xziska03.pl

CC=swipl
FLAGS=-q

all:
	$(CC) $(FLAGS) -g start -o $(PROGRAM) -c $(SRC)

clean:
	rm $(PROGRAM)
